### ISSUE TITLE
Journal editor not working with Star Wars FFG System

### ISSUE THREAD

**Issue by saif-ellafi** [ClipplerBlood/journal-improvements#9]
For some reason, the editor won't edit any pages when using the system Star Wars FFG. I am aware the system is still alpha for V10 so they are in active development, but I find it a bit strange that the journals are affected!

Best regards!

**Comment by Lyinggod** [comment]
The editor appears to work if the sidebar page is right clicked and "Edit" is selected. However when pasting in an image to the journal, the following error is created,

forgevtt-module.js:1777 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'startsWith')
    at ForgeVTT_FilePicker.upload (forgevtt-module.js:1777:20)
    at TextEditor._uploadImage (foundry.js:57703:39)
    at ProseMirrorImagePlugin._uploadImages (prosemirror.js:18130:38)
    at ProseMirrorImagePlugin._onPaste (prosemirror.js:18104:14)
    at prosemirror.js:9851:45
    at EditorView.someProp (prosemirror.js:11570:52)
    at doPaste (prosemirror.js:9851:16)
    at editHandlers.paste (prosemirror.js:9871:19)
    at view.dom.addEventListener.view.input.eventHandlers.<computed> (prosemirror.js:9323:19)
